### ISSUE TITLE
EPIC - Records Mode Redesign

### ISSUE THREAD

**Issue by thadguidry** [OpenRefine/OpenRefine#2825]
I think it would be useful to create an Epic here (series of user stories) that captures what we want in our Records mode redesign (these ideas can suffixed with linked issues and mailing list threads for further details and discussion):

From Google Research: 
> The  data  used  in  web  and  scientific  computing  is  often  non-relational.   Hence,  a flexible data model is essential in these domains. 

From Mailing List:
[The future of records mode](https://groups.google.com/forum/#!searchin/openrefine/records$20mode%7Csort:relevance/openrefine/X9O8NBC1UKQ/alxV_f3BBwAJ)

------

### Flexible Data Modeling:
- [ ] Support flexible data model representations of Records #2298 , #737 
- [ ] Nested Hierarchies
  - [ ] record row ids (server side support - ex. https://tanstack.com/table/v8/docs/api/core/table#getrowid)
- [ ] Flat Hierarchies
  - [ ] and supporting flattening nested hierarchies or column header groups - ex. https://tanstack.com/table/v8/docs/api/core/table#getallflatcolumns)  
- [ ] Table metadata (to support locale format across rows/columns - ex. https://tanstack.com/table/v8/docs/api/core/table#meta)

------

##### JSON
- [ ] Allow easier querying of data not in first normal form (multiple nested levels).
  - [ ] TODO: Research https://rumbledb.org/
    - [ ] TODO: which relies on [JSONiq](https://www.jsoniq.org/) a JSON query language
  - [ ] TODO: Research jsonpath-plus https://github.com/OpenRefine/OpenRefine/issues/2515
##### XML
- [ ] TODO: Querying XML might be slightly easier with [JSONiq Extension to XQuery](https://www.jsoniq.org/docs/JSONiqExtensionToXQuery/html-single/index.html)? 

#### Views:
- [ ] Tree lists are very useful. (and not so useful, the further you go into a tree the more difficult it is to see where you came from as the leaves can obscure the broader context of the roots)
  - [ ] IDEA: but sometimes NOT showing branches but instead only leaves(that hold values) that are the same "color" across many branches is sometimes useful. Allowing to quickly see where you came from. A complete nesting level picture.  A refreshable Accordion nav might be presented instead of Tree nav.
    - [ ] is "color" here really an alternative way to say "groups of similar or related interesting levels"? I.E. **mailing address**, and **location of birth** both have similar subfields (city, state, zip, country), I.E. [A Location](https://schema.org/location).
      - [ ] So Schema overlays (and metadata) seem to apply here at any particular nesting level?  I.E. it could be said that **mailing address** and **location** might share parts of a schema.  Giving users the power to change schema mapping of related fields would be useful and different schema views might help show users those branches with the "same color" or "similar schema".
- [ ] Branch only views?
- [ ] Zooming in/out of nesting levels to work with all records at a particular level.  An example of this would be an Icicle chart with zoom and selection as demonstrated at https://mbostock.github.io/d3/talk/20111018/partition.html
- [ ] Cascaded treemaps can more clearly and quickly show structure (shallow and deep levels) of a hierarchy even with large number of nodes. https://homes.cs.washington.edu/~jfogarty/publications/gi2008.pdf
- [ ] jsongrid.com displays nesting with simple `<div>` and `<table>` along with the `<th>` elements whenever an JSON array is found.  If a dictionary (key/value set) is found, it skips creating `<th>` for the `<table>` (as seen in the first `extra` column in screenshot.  The rendering performance I witnessed is remarkably fast due to using classes with CSS applied once and the optimized code that all browsers have nowadays for native rendering for table elements. ( mostly compositor and GPU from my performance profiling whenever I clicked to expand or collapsing the nested records and the tables use of `style="display: none"` on `<div>`) 
JSONGrid.com Screenshot:
![image](https://user-images.githubusercontent.com/986438/202634526-989038c0-4c41-441a-9837-fa9b0d870f1e.png)
- [ ] Subcomponents (to allow extension points for visual customization for example, reconcile/error metadata, row/record metadata display, etc. - ex. https://tanstack.com/table/v8/docs/examples/react/sub-components)

#### Transforming (meaning Mass Editing - this is different than Editing):
- [ ] Allow remapping a child node to a different parent node. This might be done visually by using click, drag lines between nodes somehow (examples [Quickbase](https://www.quickbase.com), [Bitwig Studio's Grid](https://www.bitwig.com/the-grid/), etc.), or just textually by filling in a form showing some Remap Node dialog (New Parent:  / Child:) 
- [ ] Transform within only a zoomed set of nesting level across all records
- [ ] Transforming sub data sometimes in arrays into columns/fields of a record #36 

#### Editing (meaning Single Editing - not Transforming):
- [ ] Allow optional single record editing mode (work with 1 parent record at a time, no grid needed?, and uses vertical representation, instead of currently multi-column horizontal representation)
- [ ] Edit within only a zoomed set of nesting level across all records

#### Navigation:
- [ ] Allow showing a Tree view navigation of hierarchical data next to the data grid (Examples: https://jsoneditoronline.org/  which uses https://ace.c9.io/) with optional filtering, sorting mechanisms in the Tree nav itself.  Another example is using Accordion style nav to always see the root levels (always knowing where you came from) https://examples.sencha.com/extjs/6.5.0/examples/kitchensink/?modern#tree-list
  - [ ] Furthermore, Accordion nav is still unwieldy when there are many root nodes, so having a search box that allows typed in text within the Accordion nav at any parent level would be better.  This would allow faster filtering of the tree nodes.  The best example I have seen that also incorporates recursive selection is demonstrated here: https://rsuitejs.com/en/components/multi-cascader

- [ ] Support tabbed navigation during Record field editing (similar quick edit experience to other spreadsheet software)  #2636 
- [ ] It would be useful during single record editing mode (vertical representation), to allow some option to click on a subfield's label or a + plus sign next to it to quickly show the grid again of flattened record fields horizontally having that particular subfield (so that tabbed navigation can be done for all records, or mass edits can be performed against all records with a given filter(s)).
  - [ ] TODO:  This needs a visual drawing for clarity.
  - [ ] Might correlate with Branch only views?  To quickly reshape the grid to work only within sets of subfields (not showing parent branches?  I.E. a way to quickly zoom in and out of the nesting levels to work and tab navigate edits within only those levels?

**Comment by wetneb** [comment]
Some discussion is here: https://groups.google.com/forum/#!searchin/openrefine/records$20mode%7Csort:relevance/openrefine/X9O8NBC1UKQ/alxV_f3BBwAJ

**Comment by thadguidry** [comment]
Hmm,  this might fit into one of the issues/stories off of this Epic. https://rumbledb.org/
Putting it under Querying for now

**Comment by thadguidry** [comment]
@wetneb Hmm, Validation (JSON Schema, etc.) probably needs to fit into the big picture here somewhere.
At import time, I can see someone using OpenRefine to validate that a particular large json file has records that do validate against a particular schema.  Conversely, at export time, they want to conform to maybe another schema.
Perhaps we need an Import/Export section to cover that.

**Comment by wetneb** [comment]
I do not think JSON validation is related to this issue.

**Comment by tfmorris** [comment]
I'd suggest that rather than thinking about a "Records-mode redesign", we instead focusing on designing ways to better satisfy the user needs that records mode is used, sometimes with great difficulty, for, as well as other related needs like JSON round-tripping. We don't necessarily need a single "mode" or tool to satisfy all the needs.

Implicit in this is going to be reworking the tree-based importers since that is one of the primary sources of "records" currently -- and the only source of column groups.

**Comment by thadguidry** [comment]
@tfmorris Records mode (fields grouped with values) currently in OpenRefine is used myriad of ways; I know this because I myself use it in ways not even Records based, but rather like Set-based or Collections-based at times.  David H. and I talked at length about various presentations of data (besides fields grouped with values) that could be done in OpenRefine.  But when it comes to Records editing...only 2 ways I've seen, Single editing of a record, and Mass editing of records.  Agree?

@tfmorris Do you also agree with the 4 scope areas of Querying, Views, Editing/Transforming, and Navigation from a high level when it comes to the concept of Records (fields grouped with values)? That's what I am traditionally used to in my domain expertise.

**Comment by tfmorris** [comment]
As a product manager, I'd collect use cases, extract the commonalities and synthesize requirements from them. I wouldn't start from technology choices or implementation details, although I might later look at how others solved similar user requirements. Users who are dealing with mostly grid data that has one column of multivalued cells might have entirely different needs from users who are trying to do round trip transforms of JSON data.

Do we have the use cases that we want to address enumerated somewhere? I know both Antonin and Martin mentioned some on the email thread, but having them all collected in one place for people review, add to, organize, etc would be a good start.

**Comment by thadguidry** [comment]
@tfmorris Do a search on "records" in our issues. https://github.com/OpenRefine/OpenRefine/issues?q=is%3Aissue+is%3Aopen+record
Collecting them and organizing the use cases into this EPIC is what I've been trying to do.  The tech examples provide context not direction or even motivation.  This is a living document that can hold links to other documents as necessary.  We wanted 1 big issue to hold it all together as an Epic (many user stories), instead of a single user story.

**Comment by thadguidry** [comment]
**Added**:  Transforming sub data sometimes in arrays into columns/fields of a record #36

**Comment by thadguidry** [comment]
An interesting idea for Records visualization of nested structure might use Bracket guides such as in VSCode's usage of faint thin lines that outer wrap the sub-records (substructures):

![image](https://user-images.githubusercontent.com/986438/169416650-2b67876e-e1af-4913-8dc3-3a84fa31d7ab.png)

**Comment by wetneb** [comment]
This issue is a bit messy and GitHub issues do not feel like the best place to have such high-level design discussions. We now have a category on the forum for such discussions, and I created a thread there: https://forum.openrefine.org/t/representing-hierarchical-data-beyond-the-records-mode/425
So I propose to close this.
