### ISSUE TITLE
EPIC - Allow opt-in to a central Reconciliation Service Registry

### ISSUE THREAD

**Issue by thadguidry** [OpenRefine/OpenRefine#3071]
**Is your feature request related to a problem or area of OpenRefine? Please describe.**
We have talked about perhaps in the future, some community member, or organization that would maintain a centralized Reconciliation Service Registry where OpenRefine could query the registry in order to stay up to date with the service's config and URL.

Unfortunately we can't put a note on old services (we don't maintain them), and since the service config and URL is initially a hard-coded config value in the OpenRefine version 3.3+ then there's no way to auto update service configurations.

Mailing list evidence of hardships of Recon services being changed or unreachable by users:
https://groups.google.com/g/openrefine/c/iAK_jQmwzA8
https://groups.google.com/g/openrefine/c/C1366ig9L4M

**Describe the solution you'd like**

We have talked in the past on various meetings about perhaps having an opt-in preference for this.
A recon service registry that can stay up to date and that OpenRefine can be allowed by users (who opt-in) to check in with that recon service registry and then auto-update the recon configs stored in OpenRefine.

Here's the start of something like a registry from @wetneb  https://reconciliation-api.github.io/testbench/
But ...

- [ ] OpenRefine versions cannot query a central service registry yet.  It would have to be hardcoded.  Related Issues: #1640 

- [X] the testbench is machine readable

- [ ] there's no status field (the registry could query each service 1 once per day to maintain a status field that OpenRefine clients could check on)

- [ ] OpenRefine doesn't have support for opt-in controls to maintain privacy concerns.  We need to make it clearer that parts of the project data are sent to a service during reconciliation. Reconciliation services themselves could advertise a URL for their privacy policy, perhaps. 

Besides the testbench pseudo-registry, there is a community maintained listing on our Wiki here: https://github.com/OpenRefine/OpenRefine/wiki/Reconcilable-Data-Sources

**Describe alternatives you've considered**
Services themselves through an Reconciliation API extension might be allowed to auto-update themselves? But this again should be opt-in and controlled by the user.
However, if Services falter then auto-update doesn't even happen, in that case, perhaps having a centralized registry for lookups can make the process (from a user perspective) more user friendly, all around where furthermore:

- [ ] The Service config UI in OpenRefine could be enhanced with providing a real-time updated listing for users to choose from upon clicking a button **UPDATE LISTING** and prompting the user for the very 1st time to opt-in and accept some agreement as necessary, etc.   Related Issues: #1658  #2916

- [ ] For example, the Service config UI in OpenRefine could be enhanced further with a small green/red icon for the Service status with **live** or **working** which could be updated from info gathered from a status field on the central registry.

**Additional context**
I plan to update any of the above pseudo-requirements of this proposed feature as our discussions on this EPIC issue progresses.

**Comment by wetneb** [comment]
Yes it could make sense to have a service catalogue in the tool itself.
The testbench is machine-readable (since it is generated from a SPARQL query).
That does not completely solve the issue though, since the location of the central catalogue will have to be hard-coded too.
As far as privacy is concerned, the catalogue itself is not a big concern, since users do not share any information (beyond their IP/browser) when requesting it. The main transfer of information happens during reconciliation itself and we could consider making it clearer that parts of the project data are sent to the service during reconciliation. Reconciliation services themselves could advertise a URL for their privacy policy, perhaps.

**Comment by tfmorris** [comment]
Properly designed distributed systems are much more resilient than centralized systems with single points of failure. Distributed is the design center for the Internet and the Web which is implemented on it.

If you read those two threads about the single reconciliation service that had flaky hosting, you'll see that significant portions of the problems were due to OpenRefine bugs:
- hang instead of error message to the user
- run reconciliation service when clicking delete
- not handling 308 hard redirects and offering the user the opportunity to follow them

Most of those bugs have been fixed and combined with support of periodic polling of updated manifests that we've discussed would fix 99% of the problem.

A centralized reconciliation service catalog *may* be interesting for other reasons, but it shouldn't be used as a crutch to avoid fixing the system so it works properly in a distributed fashion.

**Comment by thadguidry** [comment]
@tfmorris  Great points, I had the same feelings as you do Tom, where it did feel like at least informing the user within the OpenRefine client would help tremendously.  But there might be value still with some of the ideas talked about here and before with @wetneb   I don't know.  We likely need to continue working on the Reconciliation API and then asking services how they envision things additionally.  This will be a good issue to store those discussions as things progress and be able to point users and services to and ask for their feedback.

**Comment by wetneb** [comment]
Removing this label since this issue is not about a change in the API itself.

**Comment by wetneb** [comment]
Let's continue this discussion in this new issue: #4304.
