### ISSUE TITLE
Eliminate all uses of raster graphics in the UI

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/OpenRefine#6538]
This issue is here to keep track of all the raster images that we include as part of OpenRefine's UI.
We would like to migrate them to SVGs instead, for better scalability and flexibility of styling (for instance to implement a dark mode).

As we work on migrating away from those raster images, we would like to preserve (or improve) the consistency of the visual style of OpenRefine, but we don't expect pixel-perfect replacements at all.
Any help to replace those PNG files would be most welcome, even without making the associated code changes: feel free to just upload the proposed SVG replacements as a comment on this issue and someone else can take care of integrating them in the code base.

**Note:** in the [graphics](https://github.com/OpenRefine/OpenRefine/tree/master/graphics) folder we have some PSD files which you could also work from (they are likely in higher resolution)

This is the current list of PNGs:
* [ ] [main/webapp/modules/core/images/close.png](https://github.com/OpenRefine/OpenRefine/blob/master/main/webapp/modules/core/images/close.png)
* [ ] [main/webapp/modules/core/images/slider-handle.png](https://github.com/OpenRefine/OpenRefine/blob/master/main/webapp/modules/core/images/slider-handle.png)
* [ ] [main/webapp/modules/core/images/menu-dropdown.png](https://github.com/OpenRefine/OpenRefine/blob/master/main/webapp/modules/core/images/menu-dropdown.png)
* [ ] [main/webapp/modules/core/images/scatterplot-icons.png](https://github.com/OpenRefine/OpenRefine/blob/master/main/webapp/modules/core/images/scatterplot-icons.png)
* [ ] [main/webapp/modules/core/images/leftpanel-showhide.png](https://github.com/OpenRefine/OpenRefine/blob/master/main/webapp/modules/core/images/leftpanel-showhide.png)
* [ ] [main/webapp/modules/core/images/minimize-map.png](https://github.com/OpenRefine/OpenRefine/blob/master/main/webapp/modules/core/images/minimize-map.png)
* [ ] [main/webapp/modules/core/images/star-flag-map.png](https://github.com/OpenRefine/OpenRefine/blob/master/main/webapp/modules/core/images/star-flag-map.png)
* [ ] [main/webapp/modules/core/images/right-arrow.png](https://github.com/OpenRefine/OpenRefine/blob/master/main/webapp/modules/core/images/right-arrow.png)
* [ ] [main/webapp/modules/core/images/menu-opener.png](https://github.com/OpenRefine/OpenRefine/blob/master/main/webapp/modules/core/images/menu-opener.png)
* [ ] [main/webapp/modules/core/images/close-map.png](https://github.com/OpenRefine/OpenRefine/blob/master/main/webapp/modules/core/images/close-map.png)
* [ ] [main/webapp/modules/core/images/down-arrow.png](https://github.com/OpenRefine/OpenRefine/blob/master/main/webapp/modules/core/images/down-arrow.png)
* [ ] [main/webapp/modules/core/images/favicon.png](https://github.com/OpenRefine/OpenRefine/blob/master/main/webapp/modules/core/images/favicon.png)
* [ ] [main/webapp/modules/core/images/facet-resize-handle.png](https://github.com/OpenRefine/OpenRefine/blob/master/main/webapp/modules/core/images/facet-resize-handle.png)
* [ ] [main/webapp/modules/core/images/logo-gem-126.png](https://github.com/OpenRefine/OpenRefine/blob/master/main/webapp/modules/core/images/logo-gem-126.png) - #6316
* [ ] [main/webapp/modules/core/images/checks-map.png](https://github.com/OpenRefine/OpenRefine/blob/master/main/webapp/modules/core/images/checks-map.png)
* [ ] [main/webapp/modules/core/images/star.png](https://github.com/OpenRefine/OpenRefine/blob/master/main/webapp/modules/core/images/star.png)
* [ ] [main/webapp/modules/core/images/logo-openrefine-550.png](https://github.com/OpenRefine/OpenRefine/blob/master/main/webapp/modules/core/images/logo-openrefine-550.png) - #6316
* [ ] [extensions/database/module/images/more-option-horiz-16.png](https://github.com/OpenRefine/OpenRefine/blob/master/extensions/database/module/images/more-option-horiz-16.png)
* [ ] [extensions/database/module/images/more_option-vert-16.png](https://github.com/OpenRefine/OpenRefine/blob/master/extensions/database/module/images/more_option-vert-16.png)
* [ ] [extensions/gdata/src/com/google/refine/extension/gdata/logo-openrefine-550.png](https://github.com/OpenRefine/OpenRefine/blob/master/extensions/gdata/src/com/google/refine/extension/gdata/logo-openrefine-550.png) - #6316
* [ ] [extensions/wikibase/module/images/Critical.png](https://github.com/OpenRefine/OpenRefine/blob/master/extensions/wikibase/module/images/Critical.png) -> to be vectorized by #6535
* [ ] [extensions/wikibase/module/images/Information.png](https://github.com/OpenRefine/OpenRefine/blob/master/extensions/wikibase/module/images/Information.png) -> to be vectorized by #6535
* [ ] [extensions/wikibase/module/images/close-map.png](https://github.com/OpenRefine/OpenRefine/blob/master/extensions/wikibase/module/images/close-map.png)
* [ ] [extensions/wikibase/module/images/Warning.png](https://github.com/OpenRefine/OpenRefine/blob/master/extensions/wikibase/module/images/Warning.png) -> to be deleted by #6535
* [ ] [extensions/wikibase/module/images/Wikibase_logo.png](https://github.com/OpenRefine/OpenRefine/blob/master/extensions/wikibase/module/images/Wikibase_logo.png)
* [ ] [extensions/wikibase/module/images/wikidata.png](https://github.com/OpenRefine/OpenRefine/blob/master/extensions/wikibase/module/images/wikidata.png)
* [ ] [extensions/wikibase/module/images/Important.png](https://github.com/OpenRefine/OpenRefine/blob/master/extensions/wikibase/module/images/Important.png) -> to be vectorized by #6535
* [ ] [graphics/dmg_background/dmg_background.png](https://github.com/OpenRefine/OpenRefine/blob/master/graphics/dmg_background/dmg_background.png) -> can be deleted
* [ ] [graphics/row-groups.png](https://github.com/OpenRefine/OpenRefine/blob/master/graphics/row-groups.png) -> can be deleted

And GIFs:
* [ ] [main/webapp/modules/core/images/large-spinner.gif](https://github.com/OpenRefine/OpenRefine/blob/master/main/webapp/modules/core/images/large-spinner.gif) - see #5902
* [ ] [main/webapp/modules/core/images/small-spinner.gif](https://github.com/OpenRefine/OpenRefine/blob/master/main/webapp/modules/core/images/small-spinner.gif) - see #5902

Pinging @cooperzoe, since this work is relevant to the production of vector icons for the operations, some of which will be based on existing icons taken from the UI (which therefore need vectorizing in the process).

**Comment by smierz** [comment]
might be a candidate for "Good first issue" 🤔

**Comment by santiagoOrozco-encora** [comment]
Hello, I'm a fresh graduate from college and I'm starting my way to open source, I'll be happy to do the conversion and implementation, idk If you need to assign the issue or I just simply fork and work on it :)

**Comment by Abbe98** [comment]
Removing "Good First Issue" as this is attracting low quality contributions.

**Comment by SoryRawyer** [comment]
Thanks @Abbe98! Do you (or maybe @smierz as I see they've handled some of these in the past) have some guidance on how to re-make a PNG as an SVG? I know we've already got some examples of a good PR in the original post but I'm not clear on the process of actually generating the new SVG assets.

**Comment by smierz** [comment]
These files are currently unused within the project, so they probably do not need to be replaced:
* main/webapp/modules/core/images/menu-opener.png
* main/webapp/modules/core/images/star.png
* main/webapp/modules/core/images/logo-openrefine-550.png
_Note: used in gdata extension which has its [own copy](https://github.com/OpenRefine/refine-gdata-extension/blob/master/src/main/resources/com/google/refine/extension/gdata/logo-openrefine-550.png)_

Within extensions
* extensions/wikibase/module/images/close-map.png
_Note: file seems to be an unused copy of `core/images/close-map.png`_ 
* extensions/wikibase/module/images/wikidata.png

Within graphics
* graphics/row-groups.png

**Comment by tfmorris** [comment]
@smierz do you have permission to edit the list in the original description? Moving your comments inline there would make it easier to see what (if anything) remains to be done. My impression from reviewing your last few PRs is that we are almost finished.

**Comment by smierz** [comment]
Added the unused annotation inline.


It looks like the remaining files are
* [main/webapp/modules/core/images/favicon.png](https://github.com/OpenRefine/OpenRefine/blob/master/main/webapp/modules/core/images/favicon.png)
which would probably be a scaled version of existing https://github.com/OpenRefine/OpenRefine/pull/6620
* [extensions/wikibase/module/images/Wikibase_logo.png](https://github.com/OpenRefine/OpenRefine/blob/master/extensions/wikibase/module/images/Wikibase_logo.png)
* both of the spinner GIFs (maybe revive the linked PR?)


One of the PNG [graphics/dmg_background/dmg_background.png](https://github.com/OpenRefine/OpenRefine/blob/master/graphics/dmg_background/dmg_background.png) was already annotated as "can be deleted" though it is still used, so I don't know about this one https://github.com/OpenRefine/OpenRefine/blob/873965f16f23ac45b36c7acc556527602b03948d/refine#L300

**Comment by smierz** [comment]
When running the e2e tests, I noticed there are some png that are not in the project (not listed in this issue) but linked via URL, e.g.

The Wikidata logo in "Wikidata account" links to http://www.wikidata.org/static/images/project-logos/wikidatawiki.png
<img width="816" height="290" alt="Image" src="https://github.com/user-attachments/assets/3b5524df-c48d-4abf-be87-2f1214ae480a" />

The same logo is linked in "Manage Wikibase instances".
Additionally the Wikimedia Commons logo is fetched from http://commons.wikimedia.org/static/images/project-logos/commonswiki.png
<img width="704" height="370" alt="Image" src="https://github.com/user-attachments/assets/c9f3b931-762a-4bdb-9810-016ee9e04b49" />
